### ISSUE TITLE
Compiling code

### ISSUE THREAD

**Issue by ZonPV** [cryxli/sr201#3]
I bought the card SR-201-2 a while ago and want to use it for valves of my irrigation.
Not used to programming or compiling Java. Neither to Maven.
So I installed Java and Maven on my Windows 7 64-bits system, added path and environmentvariables.

Some settings
C:\SR-201>path
PATH=C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_131\bin;C:\apache-maven-3.5.0-bin\apache-maven-3.5.0\bin;

C:\SR-201>set
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_131
OS=Windows_NT
Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_131\bin;C:\apache-maven-3
.5.0-bin\apache-maven-3.5.0\bin;

I am not used to this distributed software but should like to use it. I download the original Chinese version; I can execute the .exe-file, it works a bit but that is no familiar language to me... ;-)

So glad to find this project. Unfortunately I got errors when i try to compile:

**C:\SR-201>javac MainWindow.java**
MainWindow.java:18: error: package org.slf4j does not exist
import org.slf4j.Logger;
                ^
MainWindow.java:19: error: package org.slf4j does not exist
import org.slf4j.LoggerFactory;
                ^
MainWindow.java:21: error: cannot find symbol
import li.cryx.sr201.Settings;
                    ^
  symbol:   class Settings
  location: package li.cryx.sr201
MainWindow.java:22: error: cannot find symbol
import li.cryx.sr201.SettingsFactory;
                    ^
  symbol:   class SettingsFactory
  location: package li.cryx.sr201

Can anybody telll me by examples how to create executable files for my Windows envirement?

Many thanks in advance.
Peter

**Comment by cryxli** [comment]
Säli ZonPV

**Build Tools**

You seam to have installed everything you need. But you've been using it "the old way". With `javac` you're compiling a single class, but by doing so you miss the dependent classes and all the libraries. Since I do not want to sort out all those dependencies manually, I've been using mvn.

**Compiling**

In the directory that contains the source from this repo - it is a good idea to look for a file named "pom.xml" - you can run:

`mvn install`

Maven will then read and analyse all pom.xml files which are basically its config files, then download all the required libraries and build the code against them.

If there aren't any problems, mvn will show `[INFO] BUILD SUCCESS` or something along that line. If there was a problem, mvn will also tell you. Interpreting mvn error messages may need a bit getting used to. 

**Running**

After that, you'll find an "executable" JAR file in the /target directories. From your comment I guess, you're interessted in the `C:\sr201\sr201-config-client\target\sr201-<version>-jar-with-dependencies.jar`.

These *.jar-with-dependencies.jar are simply the apps and all dependencies packed into a single file. You can execute them on windows by double clicking, or with

`java -jar sr201-<version>-jar-with-dependencies.jar`


**Foot Note about Maven**

Maven will download all dependencies into your `%HOME%\.m2\repository\` first and then copy them to the project as needed. If you plan to use mvn in the future, have an eye on that directory. It has a tendency to grow fast.

If you're using a proxy, you have to configure maven to use that proxy. You'll have to look into the mvn docs on how to do that.


**Foot Note on Executable JARs**

I know of at least three different ways to create executable JARs. And they all produce a little different output. If you cannot start the application and you get an error along the line "not an executable JAR" or "no main class found", try the other JAR from the target directory. 



That's all I can think of right now. Hope that gets you a step further.

**Comment by ZonPV** [comment]
Dear Urs,

Thanks for your quick and clear explanation! Works directly in mvn successfully. And  apllication runs too. 

At the moment no time for playing around. Thanks for your help.

**Comment by cryxli** [comment]
Happy to help.

I'll then close the ticket.
