### ISSUE TITLE
Jogging

### ISSUE THREAD

**Issue by hobpet** [cryxli/sr201#7]
Switch-commands.md should be extended with this:

## Jogging

The the basic pull-in command + "*" can be used to exectute the required command as a burst. The jog is automatically released after the relay is pulled for 0.5 seconds.
Sending the release command + "*" has no effect.

### Examples

    12*
	
Close relay 2 for 0.5 seconds and release after

Updated md is attached.
[Switch-commands.zip](https://github.com/cryxli/sr201/files/1129414/Switch-commands.zip)

**Comment by hobpet** [comment]
Sorry, \* was not properly added to the md file. (Should have press preview...)
So, here it is again:

## Jogging

The the basic pull-in command + "\*" can be used to exectute the required command as a burst. The jog is automatically released after the relay is pulled for 0.5 seconds.
Sending the release command + "\*" has no effect.

### Examples

    12*
	
Close relay 2 for 0.5 seconds and release after
[Switch-commands.zip](https://github.com/cryxli/sr201/files/1129421/Switch-commands.zip)

**Comment by cryxli** [comment]
There is such a command? Will add it later today.

**Comment by hobpet** [comment]
Chapter 5.5 in the attached document. (Google translate is my friend!)
[SR-201系列产品说明书.pdf](https://github.com/cryxli/sr201/files/1130982/SR-201.pdf)

**Comment by cryxli** [comment]
Now I remember! I had that document translated earlier. But I could not make sense out of the Asterix and the K-Command. Here is why:

You will probably agree, that the action

    send "11*"

translates into the manual actions

    send "11"
    wait 500 ms
    send "21"

That corresponds to the behaviour described under 5.5. But it also states that

    send "21*"

should translate to

    do nothing

but it actually translates to

    send "11"
    wait 500 ms
    send "21"

too. I just verified that again with my board.

Last time I stopped here, because I didn't want to document a feature I do not understand. This time I went a step further: It seems that the STATE is ignored completely. Therefore, the action

    send "-X*"

which consists of an illegal BASIC_COMMAND should translate to

    send "1X"
    wait 500 ms
    send "2X"

Which it does, indeed.

That leads to the simplification that the JOG_COMMAND consists of any one byte followed by any CHANNEL followed by an asterix.

@hobpet, by any chance, can you verify my observation?

**Comment by hobpet** [comment]
Of course, I will test this with my board.

**Comment by hobpet** [comment]
I can confirm that the first character is completely ignored. It even worked with some weird special ASCII characters, like ALT-0147 (“1\*).

**Comment by cryxli** [comment]
Tried to describe out observations in the [Switch commands](https://github.com/cryxli/sr201/wiki/Switch-commands) section.

**Comment by hobpet** [comment]
Looks great, thanks!
